### ISSUE TITLE
User Onboarding Survey

### ISSUE THREAD

**Issue by yeqbfgxjiq** [aracred/onboarding#4]
# The MVP of AraCred user onboarding

Aracred processes and batch mints cred in DAOs. however it is not as autonomous as it could be, collecting user data and adding them to the whitelist is a huge bottleneck.

### Potential solution

[AraCred Onboarding Google Form](https://docs.google.com/forms/d/1o5_yKGh_XzFiePOIQqKe2ginjeKGgjPqjZS7aawb6l0/edit) => [AraCred Onboarding Google Sheet](https://docs.google.com/spreadsheets/d/1oxcdo5iVK3_XdOyJu-6x9UGAvauQEfMacXruW8WMUPg/edit?usp=sharing) with responses.

Use Google forms for the front end, attach it to a google sheet, pull the data out using google's API. 

### Update

It would be nice to call GitHub Actions directly pull data from Google Sheets, but the workflow doesn't appear to work.

### Open Question

Could we use [Airtable](https://airtable.com/) instead?

**Comment by luisivan** [comment]
It seems like this would be redundant with https://github.com/aracred/bot/, right?

**Comment by yeqbfgxjiq** [comment]
Yeah totally
