### ISSUE TITLE
Automagically gather users from GitHub, Discord and Discourse

### ISSUE THREAD

**Issue by luisivan** [aracred/onboarding#6]
Right now the maintainer of the AraCred instance needs to [manually input](https://aracred.github.io/website/docs/deploymentOverview#step-2-connect-github-optional) contributors to `project.json`.

As users will have [an onboarding process](https://github.com/aracred/onboarding/issues/1), we could automate this and automatically add entries to `project.json` and `addressbook.json`.

**Comment by luisivan** [comment]
We could end up with gigantic JSON files very easily. We also need a server which will add these users to a database. Idea:
- We can use [LowDB](https://github.com/typicode/lowdb) to store addresses in a `dist` branch of the repo
- We can use [Now](https://now.sh) to automatically deploy a frontend where users can link their GitHub/Discord/Discourse user and their Ethereum address
- The backend on Now could be logged in as a GitHub bot set up for that particular AraCred instance, and modify the LowDB database adding the details from users
- Then GitHub actions runs and generates new scores for all users

**Comment by luisivan** [comment]
Question now: What is the threat model?

We could really simplify this if there was a single server where users can link their profiles, with a single database, and also a single GitHub bot that runs actions. That would essentially be a centralized service, and a single bot would have total control over all the tokens. That doesn't seem advisable.

If we want to go the more decentralized approach, where just one person (the person who sets it up) has control over an instance of AraCred (because they/their bot has commit access and access to Actions). But then they either need to run GitHub actions with their personal account or create a new bot just for that instance.

**Comment by yeqbfgxjiq** [comment]
@luisivan There's many layers of permissioning here:
- The ability to add identities to the SourceCred identities plugin (the part of `project.json` that links names with GitHub, Discord, etc...) as well as Ethereum addresses to the `addressbook.json`.
- The ability to calculate (and thus verify) Cred scores (on Discord you need a permissoined bot to fetch that data whereas GitHub and Discourse are relatively open)
- The ability to mint tokens. The recommended settings here is a 0% quorum so the vote will automatically pass, but if anyone objects they can veto it. The Aragon Court can also be dropped in for further protection. 

All in all, for an MVP intended to produce scores for projects during a hackathon and distribute kudos to contributors the thread model scenario isn't really a priority. For more serious projects @mzargham and I are modeling out the game theory and tokeneconomics of AraCred. This will highlight the various governance mechansisms that can be used to modulate token minting as well as the economic bounds within which the system works and does not work (aka don't flood the market).

**Comment by yeqbfgxjiq** [comment]
Regarding simplifying the setup process:
- Providing "AraCred as a Service" could be an easy way to simplify setup for new users. This would require some dev-ops, however, which is way outside of the scope of the MVP so that would be down the road once AraCred is working and validated in the wild.
- Until then, creating a simple deployment flow that anyone can follow (and offering to help people set this up) is the way to go. We have docs for that here: https://aracred.github.io/website/docs/deploymentOverview/. Adding the feature to spin up a user onboarding front-end to this process would be great. The goal is to have this ready to go by the end of the week so that we can onboard projects before the end of Dragon Quest.

**Comment by luisivan** [comment]
> The recommended settings here is a 0% quorum so the vote will automatically pass, but if anyone objects they can veto it. The Aragon Court can also be dropped in for further protection.

That is perfect. Being that the case, both the users database (linking their profiles + addresses) and the @aracredmvp bot can be centralized, which makes it all easier!

**Comment by yeqbfgxjiq** [comment]
Yup! Trying to reduce complexity as much as possible. That way the off-chain aspects can be fast and easy, and then we use on-chain governance mechanisms such as token-holder voting and/or the Aragon Court to approve and/or block actions that have governance and economic consequences.

**Comment by luisivan** [comment]
Boom https://github.com/aracred/bot
